Taking the concepts from @boninodasilvasantos2022personal, @tbl-mapping-pht-dssc maps the PHT architecture to the DSSC Blueprint 2.0 (DSB2). Some mappings are relatively evident. For example, the concept of Data and Metadata as defined in PHT is subsumed in the concept of a Data Product in DSB2. Less evident, is the mapping of the notion of a Train:

> A Train represents the way data consumers interact with the data available in the Data Stations. Trains represent a particular data access request and, therefore, each train carries information about who is responsible for the request, the required data, what will be done with the data, what it expects from the station, etc.

to Value Creation Services in DSB2 that includes data fusion and enrichment, collaborative data analytics and federated learning. More specifics of this mapping will be provided in the Archimate specification.

+-----------------------+-------------------------------------------------------------------------------------------------------------+
| Component PHT         | mapping to DSSC Blueprint 2.0 concepts                                                                      |
+:======================+:============================================================================================================+
| - Data Station        | - Data Space Building Block                                                                                 |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Data                | - [Data Product](https://dssc.eu/space/BVE2/1071253231/Data+Space+Offering#3.1.-Data-products)              |
| - Metadata            |                                                                                                             |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Data Controller     | - Data Rights Holder                                                                                        |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Station Controller  | - Data Product Provider                                                                                     |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Personal Gateway    | - included in Participant Agent Services                                                                    |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Station Directory   | - included in Federation Services                                                                           |
|                       | - Catalogue provisions and discovers offerings of data and services in a data space                         |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Directory Owner     | - Common Intermediary provides federation services that are common to all participants of the data space    |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Train               | - Value Creation Services                                                                                   |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Train Provider      | - Service Provider                                                                                          |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Train Handler       | - specialization of Data Space Component that realises the Train Value Creation Service                     |
+-----------------------+-------------------------------------------------------------------------------------------------------------+
| - Train Owner         | - included in Service Provider as most generic role                                                         |
|                       | - concept of Intermediary (specialization of SP) is closer to definition of Train Owner                     |
+-----------------------+-------------------------------------------------------------------------------------------------------------+

: Mapping the key concepts from the PHT architecture [@boninodasilvasantos2022personal] to the [concepts of the DSSC Blueprint 2.0](https://dssc.eu/space/BVE2/1071252161/Alphabetical+List+of+All+Defined+Terms+in+Blueprint+v2.0). {#tbl-mapping-pht-dssc}

TO DO:

- Explain that [FAIR Data Point](https://specs.fairdatapoint.org/fdp-specs-v1.2.html) specification only contain part of the functionality of a data station, namely just the metadata and catalog. 
- Initiative has started to extend the paper by @boninodasilvasantos2022personal into a full specification, named the [FAIR Data Train](https://specs.fairdatatrain.org/)
- One of the key questions of this paper is to detail [the 'data conformity zone' as defined in the Cumuluz canvas](https://www.vzvz.nl/media/downloads/canvas-voor-databeschikbaarheid-v11-003pdf/download) as the functionality through which the data station is populated


## Comparative analyses of existing data stations

This section provides a detailed comparative analysis using the concepts of the PHT architecture of how the "data station" concept is realized in existing federated data systems:

- the Dutch PLUGIN federated network [@kapitan2025data] as an example of data stations that are focused on federated learning [@rieke2020future] 
- the Swiss SPHN network [@sphn] as an example of a data station that uses graph databases both for the data and metadata
- the Fair Data Cube [@liao2024fair] as an example of a graph-based data station combined with federated learning
- the Datastation-as-a-Service as defined by the Zorginstituut for federated analytics using privacy-enhancing technologies [@2024kikv]
- TO DO: data station as defined by Cumuluz
